jobs:
- job: localhost_scan
  displayName: "Localhost Scan"
  pool:
    name: default  # Use Windows agent
  steps:
  # Step 1: Checkout repository
  - checkout: self
    displayName: "Checkout Repository"

  # Step 2: Create output directory
  - script: mkdir "$(Pipeline.Workspace)\output_fold"
    displayName: "Create Directory"

  # Step 3: Run Checkmarx DAST scan
  - task: Bash@3
    displayName: "Run Checkmarx DAST"
    env:
      CX_APIKEY: $(CX_APIKEY)
    inputs:
      targetType: inline
      script: |
        docker run --rm --network="host" `
        -e CX_APIKEY=$(CX_APIKEY) `
        -v "$(Pipeline.Workspace):/work-folder" `
        checkmarx/dast:latest web `
        --configFull "/work-folder/localhost_config.yaml" `
        --base-url "https://ind.ast.checkmarx.net" `
        --environment-id "83c1c65d-db18-475c-a1a6-1fe068b38020" `
        --output "/work-folder/output_fold"

  # Step 4: Publish results
  - task: PublishPipelineArtifact@1
    displayName: "Publish Scan Report"
    inputs:
      targetPath: "$(Pipeline.Workspace)/output_fold"
      artifact: scan-report
