jobs:
- job: localhost_scan
  displayName: "Localhost DAST Scan"
  pool:
    name: Default  # Make sure to set this to your local agent pool if needed
  steps:
  # Step 1: Checkout repository
  - checkout: self
    displayName: "Checkout Repository"

  # Step 2: Create output directory
  - script: |
      if (-not (Test-Path "$(Pipeline.Workspace)\output_fold")) {
          New-Item -ItemType Directory -Path "$(Pipeline.Workspace)\output_fold"
      }
    displayName: "Create Output Directory"

  # Step 3: Run Checkmarx DAST scan using PowerShell
  - task: PowerShell@2
    displayName: "Run Checkmarx DAST"
    env:
      CX_APIKEY: $(CX_APIKEY)
    inputs:
      targetType: inline
      script: |
        # Run Docker Checkmarx DAST CLI scan
        docker run --rm --network="host" `
        -e CX_APIKEY=$(CX_APIKEY) `
        -v "$(Pipeline.Workspace):/work-folder" `
        checkmarx/dast:latest web `
        --configFull "/work-folder/localhost_config.yaml" `
        --base-url "https://ind.ast.checkmarx.net" `
        --environment-id "83c1c65d-db18-475c-a1a6-1fe068b38020" `
        --output "/work-folder/output_fold"

  # Step 4: Publish results
  - task: PublishPipelineArtifact@1
    displayName: "Publish Scan Report"
    inputs:
      targetPath: "$(Pipeline.Workspace)/output_fold"
      artifact: scan-report
