trigger:
  - main

pool:
  vmImage: 'ubuntu-latest' 

steps:

  # Simple script task (Hello world)
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  # Multi-line script task
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'

  - task: Checkmarx AST@2
    inputs:
      CheckmarxService: 'CheckmarxOne Connection'
      projectName: 'test1'
      branchName: 'main'
      tenantName: 'checkmarx-global-services-internal'