name: MERN WebApp CI/CD with DAST Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug Directory Structure
        run: find . -name "package.json"

  install_dependencies:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug Directory Structure
        run: ls -la

      - name: Install Dependencies
        run: npm install
        working-directory: ./ # Update `subdir` to the folder containing `package.json`

  tests:
    needs: install_dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: npm test
        working-directory: ./ # Update `subdir` to the folder containing `package.json`

  dast_scan:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Checkmarx DAST Scan
        uses: Checkmarx/dast-github-action@v2.3.0
        with:
          command: web
          config: 'zapconfig.yaml'
          base_url: ${{ secrets.VERCEL_DEPLOYMENT_URL }}  # URL of your deployed app on Vercel
          environment_id: ${{ secrets.CX_ENVIRONMENT_ID }}
          verbose: true
          fail_on: 'HIGH'
          timeout: 12000
          log_level: info
