name: Checkmarx Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest
    
    env:
      CX_FLOW_ENABLED_VULNERABILITY_SCANNERS: sast
      CX_TEAM: "/CxServer/"
      CX_USERNAME: ${{ secrets.CX_USERNAME }}
      CX_PASSWORD: ${{ secrets.CX_PASSWORD }}
      CX_BASE_URL: ${{ secrets.CX_URL }}
      CX_CLIENT_SECRET: ${{ secrets.CX_CLIENT_SECRET }}
      CX_BUG_TRACKER: "Sarif"  # Change to "Jira" if using Jira bug tracker

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Checkmarx Scan
        run: |
          echo "Starting Checkmarx Security Scan..."
          curl -X POST $CX_BASE_URL/api/scans/submit \
            -H "Authorization: Bearer $CX_CLIENT_SECRET" \
            -d "team=$CX_TEAM&project=$CX_PROJECT&preset=$CHECKMARX_PRESET&bug_tracker=$CX_BUG_TRACKER"
          
    # Optional: Artifacts for storing reports
    # artifacts:
    #   paths:
    #     - checkmarx_report/
    #   when: always
